theme: jekyll-theme-minimal
title: PJ Adeleke Portfolio
description: Bookmark this to keep an eye on my project updates!

---
layout: page
title: About Me
permalink: /about/
---

---
layout: page
title: Projects
permalink: /projects/
---
